builds:
  - "genome"
  - "E1"
strain_id_field: "accession"
files:
  auspice_config: "defaults/auspice_config.json"
  description: "defaults/description.md"
  exclude: "defaults/dropped_strains.txt"
  genome:
    auspice_title: "Real-time tracking of Rubella virus full genome evolution"
    clades: "defaults/clades_genome.tsv"
    genemap: "defaults/genemap_genome.gff"
    include: "defaults/include_strains_genome.txt"
    reference: "defaults/reference_genome.fasta"
  E1:
    auspice_title: "Real-time tracking of Rubella virus E1 gene evolution"
    clades: "defaults/clades_E1.tsv"
    genemap: "defaults/genemap_E1.gff"
    include: "defaults/include_strains_E1.txt"
    reference: "defaults/reference_E1.fasta"
filter:
  group_by: "country year"
  genome:
    min_length: 7000
    sequences_per_group: 20
  E1:
    min_length: 700
    sequences_per_group: 200
refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4
ancestral:
  inference: "joint"
traits:
  columns: "region"
tip_frequencies:
  min_date: "2010-01-01"
  # 0.083 = 1 / 12 (one month)
  narrow_bandwidth: 0.083
  # 0.250 = 3 / 12 (three months)
  wide_bandwidth: 0.250
  proportion_wide: 0
  pivot_interval: 1
